### ISSUE TITLE
PowerOff activity?

### ISSUE THREAD

**Issue by aaronwolen** [KraigM/homebridge-harmonyhub#21]
Thanks for writing/maintaining such a useful plugin. 

I've been trying to figure out a way to create a "good night" scene that will shut off my current Harmony activity, whatever it is, without success. I noticed that during initialization, homebridge-harmonyhub lists an activity called `PowerOff` but it isn't available in any of the HomeKit configuration apps.

Is `PowerOff` supposed to be a trigger that users can access? Or is there a better way to accomplish what I'm trying to do?

**Comment by KraigM** [comment]
I have that exact thing setup on my HomeKit (goodnight -> power off) :smile:  

The way it works _power off_ is an activity but instead of exposing it like the other activities, instead I tied it to every other activities off state. So all you have to do is tell Siri to ensure all your activities are off on the good night scene

**Comment by KraigM** [comment]
I have never tested it with multiple since I currently only have the one activity. But I'm guessing Siri only calls _off_ if it is currently in an _on_ state so that's why I'm guess you will have to specify all. But if Siri sends off regardless then you just need one since all the off states are tied to the same activity.

**Comment by aaronwolen** [comment]
You're right. I setup the goodnight scene as you suggested, adding all activities in the "off" state and it worked. Thanks for the help!

**Comment by andrei4002** [comment]
I'm seeing a possible issue here, not sure what's going on. So I have 2 hubs and I keep getting an "Cannot add a bridged Accessory with the same UUID" error from this plugin. my guess is that it might be related to having the same activity name (PowerOff) for multiple hubs (names must not collide?)

**Comment by KraigM** [comment]
@andrei4002  what version of homebridge-harmonyhub are you using?

with the current version (0.1.1) its likely because you registered the platform twice but didn't specify the IP addresses so it just found the same hub for both

with the prerelease version (0.2.0) its likely because you registered the platform twice (now one platform will handle multiple hubs).

**Comment by KraigM** [comment]
@andrei4002 Also in the future (unless the bug is definitely related) you should create a new issue instead of adding a comment to another, unrelated, closed issue.  The only reason I knew you wrote something on it was because I got an email.  Had I missed/ignored the email it prob would have never been answered 😜
