### ISSUE TITLE
Siri commands for HarmonyHub

### ISSUE THREAD

**Issue by JangoBritt** [KraigM/homebridge-harmonyhub#33]
So I've been playing around with the Elgato Eve app, to configure my Harmony on Homebridge, and it's not the simplest thing to control 

My Activities on the Harmony are called Freeview, Watch Apple TV, and Play XBOX One. 

This is because you can't call the activity the same as a device, which sucks

Now I've renamed the activities on Eve to Apple TV and XBOX, but it's not playing ball. 

With the activities all in a room called Living Room, if I say 'switch living room Xbox on', it switches on the Freeview activity. Why is it activating the wrong command? Further, in Eve, the Freeview is reporting as On

If I just say 'Switch Xbox on', it doesn't know what I mean. With my LightWaveRF stuff, if I say 'Switch LEGO street on,' it switches on the Office LEGO street, without having to say 'office'

Odd!

**Comment by digiltd** [comment]
It sounds like it might be cache issue perhaps?

When you say "switch living room Xbox on" does Siri transcribe it correctly? I had trouble with "Kodi" as it always thought i meant "Cody". I then thought I would be clever and create a room called "Harmony Hub"  so I could say "Switch on Mac Mini in the Harmony Hub". Siri being Siri was hearing "Harmony" was "How many"

Not sure if it matters but try "switch on the Xbox in the living room" with and without the room.

Are you using the master branch of the plugin? Kraig has been working on a new version of the plugin and it is currently in alpha if you want to try it (at your own risk of course).

**Comment by JangoBritt** [comment]
I'm using the master branch

What was strange is that Siri knew what I was saying, and would send the command to switch on the Xbox... But Homebridge was issuing the command to switch on Freeview. Siri times out waiting for a response back from Xbox, because it was Freeview that was being switched on.

**Comment by jer78** [comment]
I kinda have the same problem and I believe the issue is when you say the room it turns on all devices in that room. I'm thinking it's a HomeKit problem. I have a few activities in the living room and another harmony hub in the bedroom. If I say "turn on the living room TV" it goes through all the 5 harmony activities in the living room and also turns on my hue lamp. The work around is to name the living room activities different from the bedroom ones and not ever say the room. It's annoying but hopefully there will be a fix soon.

**Comment by KraigM** [comment]
Ah yes, what is the name of your TV activity.  If it is for instance is named "Watch TV" then you would have to say "Turn on the living room watch TV" which still may very confuse Siri.

The problem is that Siri treats "Living Room" as the name of a room. Therefor it tries to find a device named "TV", if it cannot, it oddly assumes that you wanted to turn on every switch in the living room.

The best solution is to name the activity's **service name** (not accessory name) in HomeKit to something Siri can clearly understand.  For me, in HarmonyHub my activity is still called "Watch TV" but in HomeKit I simply named it "TV" so I can say "Turn on the living room TV" and Siri properly understands it.

**Comment by JangoBritt** [comment]
What... So rename it in the config.json? Mine aren't specified, but discovered from the hub. 

I already have it renamed from Watch Xbox One to just XBOX in the HomeKit config (you don't think it could be a capitalisation issue, do you?)

I'll give "switch on the Xbox in the Living Room" a try when my son is finished with Peppa Pig. Lol

I've tried just "switch on the Xbox", but it goes off and googles what I've just said. 

I have to say, Siri is one pedantic bitch.... I have a zone called "Bedrooms" she won't respond to "Switch off all the bedroom lights" only "Switch off all the bedrooms lights.

**Comment by dalewright** [comment]
@KraigM Thanks for the advice on Siri names. That worked a treat! 

Has anyone managed to use Siri to turn off their setup? 

I can use Siri or my various HomeKit app's to trigger an activity but I cant figure out how to turn anything off.

**Comment by jer78** [comment]
Just say "turn off <any activity>". It doesn't matter if it was the one running or not.

**Comment by JangoBritt** [comment]
So 'Switch off the Xbox in the Living Room' is working fine  

What Kraig said about the whole room activity looks about right. I caught the to cycling through the activities one time I tried it (switched to HDMI2 for Apple TV, then back to HDMI 1 for the Xbox)

So it seems the fickle cow Siri has to be spoken to in just the right way... No comment. Lol

So if I only have one Xbox in my Homebridge, why doesn't just "Switch on the Xbox work?

**Comment by digiltd** [comment]
@JangoBritt have you tried saying "turn off/on" instead of "switch on/off"? 

That sometimes helps with me, though never consistently enough to ever understand what is going on with HomeKit.
