### ISSUE TITLE
Error with 0.2.0 alpha

### ISSUE THREAD

**Issue by jer78** [KraigM/homebridge-harmonyhub#34]
So I tried the new alpha version and am getting the following error:

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: bind EADDRINUSE 0.0.0.0:5224
>     at Object.exports._errnoException (util.js:856:11)
>     at exports._exceptionWithHostPort (util.js:879:20)
>     at dgram.js:213:18
>     at doNTCallback3 (node.js:463:9)
>     at process._tickCallback (node.js:369:17)
>     at Function.Module.runMain (module.js:459:11)
>     at startup (node.js:138:18)
>     at node.js:974:3

I am running older versions of node 5.1.1 and NPM 3.8.2

**Comment by KraigM** [comment]
Do you have multiple definitions of the HarmonyHub in you platforms?  Even if you have multiple hubs you should only use one now.

**Comment by jer78** [comment]
Ah, yes I do. I didn't think of that. I'll try again

**Comment by jer78** [comment]
Working like a charm now. I'll let you know if there's any issues going forward. Thanks for the lightning quick support!!

**Comment by jer78** [comment]
So here is my first impressions of the 0.2.0 version:

It is a little more difficult to control with apps since each hub now has activities listed under power states. Is there a way to change either 1) it back so each activity displays as its own device or 2) the power states are named after the activities instead of just "power"?

I also noticed it's remarkably slower response time than the 0.1.1 release. I'll test some more but I often Siri responds, "i did not hear back..."

**Comment by KraigM** [comment]
Can you check and make sure your HarmonyHub itself is up to date?  

Yes the plugin no longer immediately assumes it worked, nor does it constantly ask the hub what is the current activity.  

Instead the hub now tells the plugin that the state changed (or rather I started making use of that) so as soon as it says it is in the process of starting an activity I treat it as started.  When you change the activity, instead of blindly assuming everything is going to be fine, I wait for either the hub to say that it is starting to change the activity to the desired activity or (worse case) it waits until the request to change it has been complete.

For me, when I start it I get a state changed notification almost immediately. On start it is about 20-30 seconds later when it finally is turned on but Siri acknowledges that it is on as soon as the notification comes in (a second or less for me).

**Comment by jer78** [comment]
actually it's just as fast as before. The problem was with my activity naming for Siri was causing multiple activities to launch hence locking it up for a few minutes. I solved it by getting my former naming convention and I also figured out this version works much better with an activity named  "Living Room Music". Before it would start every activity in the living room but now it seems to recognize just that activity. All is working well! Thanks again for all your hard work!!

**Comment by KraigM** [comment]
Awesome! Glad to hear. Yeah it should be a lot faster now, stay connected better, and detect changes as soon as they happen (i.e. you could now have HomeKit auto trigger other HomeKit devices to change in response to an activity changing and even if you use the harmony remote to change the activity the other devices should react almost immediately).

As for the "Power" name, unfortunately without using custom characteristics (which will remove the possibility of using Siri) there is nothing I can do.  I can change the display name but since the display name currently is "On" I would assume the app you are using is ignoring the display name property.

I can go back to having them split up into separate devices but that causes issues for people with multiple hubs (like you).  

Plus the way Apple designed HomeKit is that one physical device = one accessory in HomeKit and if that device has multiple conceptually separate pieces of functionality (like a ceiling fan might have a light as well as the fan), they should each be a service.  Beyond that, if a service has multiple settings, it would create a characteristic for each.

That all being said, to follow this guideline, each hub has activities that can change several different other physical devices, so the main physical device would be the hub, therefore all the activities should be in the hub.  Since (in the future) we could potentially expose the various controls associated to each activity (volume level, mute, etc) and since I don't think Siri would understand if all the activities were custom characteristics, that leaves the activities being services associated to their hub accessory.

I had brought up all of this in the #slack channel and the only people who responded agreed that it makes more sense to properly follow HomeKit since it would also solve a lot of issues for those with multiple hubs.  I also asked if I should create an option to do it the old way and split it up (since some apps don't understand one accessory having multiple on/off switches) and others said that it shouldn't be necessary and it would more likely just cause problems.

I can try to see if changing the "display name" makes any difference for you, but I highly doubt it will.  

The app I am currently using (Home) does it right; the standard view displays each service so you see the service name (which is the activity name by default) so it is very clear.  But its not a cheap app ($15).

Elgato Eve finally updated their app (which is free) and it now includes the service name as well as the accessory name so it is clear which activity that "Power" is referring to.

If you disagree with any of that or have any thoughts, concerns, ideas, etc you should def jump on the #slack channel.  There is one specifically for this plugin.

**Comment by jer78** [comment]
Makes perfect sense. Don't let me derail you here, I'm no HomeKit expert, just an over ambitious user at this point. :) Sure, I'll definitely join the #Slack channel.

**Comment by jer78** [comment]
Is there instructions somewhere on how to join your #slack channel?
